### ISSUE TITLE
List of examples homemaker toml configs (from real systems)?

### ISSUE THREAD

**Issue by dmix** [FooSoft/homemaker#1]
It would be awesome if the README/wiki had some example .toml config files, ideally from real systems. There are a lot of dotfiles on Github, maybe a community section that can collect links to them?

The documentation is solid otherwise. Love the software.

**Comment by FooSoft** [comment]
Yeah, that's a good idea. I was going to put my own huge toml config file on the GitHub page too, just haven't gotten around to it yet. It uses pretty much every feature Homemaker has to offer.

**Comment by FooSoft** [comment]
Section added
