### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by RickCogley** [FooSoft/homemaker#11]
Hello Alex @FooSoft,

Thank you for your work on homemaker. I'm considering to use homemaker to manage dotfiles on my macs and *nix machines. Just wondering a couple things if you don't mind: 
- how does one handle the situation where, if you have homemaker install some app, say via `brew` on mac, and that app creates basic skeleton dot files: does homemaker automatically overwrite those? 
- I _think_ I understood that the homemaker environment variables default to certain values, and I noticed in your sample toml file, that you are referencing them. Do they need to be set before running homemaker? Are all of them defaulted?
- does homemaker support symlinking a file into ~ that is present in a separate cloned git repo? I use taskwarrior and have my tasks and its rc file in a separate private repo. 
- probably not homemaker-related, but, do you happen to have a good way to handle data that you would not want to store in a public repo? I see homemaker can be used to bootstrap a system pretty thoroughly, but what about things like my private encryption keys. Is there a good way of automating that? 

Appreciate your help, thanks.
--Rick

**Comment by FooSoft** [comment]
Hey Rick, thanks for checking out Homemaker.

> how does one handle the situation where, if you have homemaker install some app, say via brew on  mac, and that app creates basic skeleton dot files: does homemaker automatically overwrite those?

This is a common situation and Homemaker can delete the target files and replace them with symlinks if you provide the `-clobber` command line argument. If you do not, it will ask you what to do on a case-by-case basis. 

> I think I understood that the homemaker environment variables default to certain values, and I  noticed in your sample toml file, that you are referencing them. Do they need to be set before running homemaker? Are all of them defaulted?

There are five environment variables set by Homemaker automatically, they are `HM_CONFIG`, `HM_TASK`, `HM_SRC`, `HM_DEST`, and `HM_VARIANT`. You can see a description of what they do in README.md. You can also set your own environment variables using the `envs` enumeration through the config file. 

> does homemaker support symlinking a file into ~ that is present in a separate cloned git repo? I use taskwarrior and have my tasks and its rc file in a separate private repo.

Homemaker doesn't know or care about git. If the files are in your file system Homemaker can link them. Relative paths are resolved with `HM_SRC` and `HM_DEST`, but you can also just provide absolute directories. 

> probably not homemaker-related, but, do you happen to have a good way to handle data that you would not want to store in a public repo? I see homemaker can be used to bootstrap a system pretty thoroughly, but what about things like my private encryption keys. Is there a good way of automating that?

I just run `gpg` with symmetric crypto as part of a task:

```
[tasks.backup]
    cmds = [
        ["@install", "duplicity", "s3cmd"],
        ["gpg", "--output", ".s3cfg", "--decrypt", "$HM_SRC/.s3cfg.gpg"],
    ]
```

Cheers, and let me know if you have any other questions.

**Comment by RickCogley** [comment]
Hi Alex @FooSoft, thanks for the above. I'm working through this now, and am just wondering: is packer something present on most Linux distros these days? 

Kind regards

**Comment by FooSoft** [comment]
[Packer](https://aur.archlinux.org/packages/packer/) is an [Arch Linux](https://www.archlinux.org/) specific tool, and you most definitely won't find it on other distributions. If you want to use Homemaker to install programs across different distros, check out the `variants` feature.

**Comment by RickCogley** [comment]
Thanks Alex. Well, I ran `packer` on my recently-installed CentOS 6.2, and it indeed was on there. It might be referring to: https://www.packer.io/ though. Anyway, noted that what you mean by it is, the Arch Linux tool, either way. I'll set up `install__mac` or `install__redhat` etc.
