### ISSUE TITLE
AUR package

### ISSUE THREAD

**Issue by DylanSimowitz** [FooSoft/homemaker#14]
I created an AUR package for arch linux distributions available here https://aur.archlinux.org/packages/homemaker-git/

Let me know if you want ownership or maintainer status.

**Comment by FooSoft** [comment]
Hey, that's pretty sweet! I've used Arch in the past, but I'm on Fedora now; if you can make me co-maintainer, that would be cool :+1:

**Comment by DylanSimowitz** [comment]
Added you as a maintainer. Thanks for this great software :smiley:
