### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by breml** [FooSoft/homemaker#15]
Thank you very much for this very useful tool. I did some testing and so far I really like what I see and I am thinking about replacing my current solution for the management of my dotfiles.
I could also imagine to contribute to your tool and therefore I would like to ask you to add a license to this tool, so that there is clarity about the terms.

**Comment by breml** [comment]
I realized, that the MIT license is present in every source file. Maybe it would be easier to just have a license file in the project root directory. To me it looks like it is quite common to have it this way.

**Comment by FooSoft** [comment]
I like to have license information in source files so that if the individual modules are reused, it is clear what license they are released under. That being said, it also just makes sense to add a `LICENSE` file, so I've added one :+1:
