### ISSUE TITLE
Comments in arrays

### ISSUE THREAD

**Issue by dmix** [FooSoft/homemaker#2]
The TOML standard and go library support comments in arrays

https://github.com/toml-lang/toml/issues/340
https://github.com/naoina/toml

But doing this in Homemaker:

``` TOML
    links = [
        # Core dotfiles
        [".zprofile", "zsh/zprofile"],
        [".zlogin", "zsh/zlogin"],
        [".zshrc", "zsh/zshrc"],

        # Directory shortcut
        ["zsh", "zsh"],
    ]
```

Causes an error:

```
2015/08/06 17:56:17 toml: line 68: parse error
```

**Comment by FooSoft** [comment]
This appears to be problem with the toml parser that I'm using for Homemaker; I've submitted a in issue regarding this: naoina/toml#10. You mentioned that the library supports comments inside of arrays, but I couldn't find an example of this actually working (it seems like it should though). 

Homemaker itself doesn't do any config parsing by itself, so this is definitely a parser issue.

**Comment by dmix** [comment]
There is another popular go TOML library with good comment support:

https://github.com/pelletier/go-toml

Although it doesn't have the nice toml.Unmarshal function as the current library.

**Comment by wlcx** [comment]
I have used https://github.com/BurntSushi/toml a fair bit before, the number of stars suggest it is the go-to! (ho ho)

**Comment by FooSoft** [comment]
Fixed, new binaries uploaded :smile:

**Comment by dmix** [comment]
lovely, thanks :+1:
