### ISSUE TITLE
i386 Linux binary doesn't work in Ubuntu 10.04 (2.6.32-74)

### ISSUE THREAD

**Issue by christopher-demarco** [FooSoft/homemaker#3]
Attempting to run the binary fails with:
    2015/08/27 12:32:05 user: Current not implemented on linux/386

I'll just install golang on the system in question, but thought you might like to know about it.

Thanks for the great tool!

**Comment by FooSoft** [comment]
Thank you for the report. I believe that this happened because I did a cross compile on my laptop which was not completely set up, so the non amd64 builds are probably busted. Will put up new ones when I return home tomorrow.

**Comment by FooSoft** [comment]
This is now fixed and new binaries are uploaded
