### ISSUE TITLE
libpthread.so.0 not found on OSX 10.10.5

### ISSUE THREAD

**Issue by christian-schulze** [FooSoft/homemaker#5]
Using the provided `homemaker_darwin_386.zip` pre-built binary on OSX 10.10.5, I get the following error running homemaker:

> dyld: Library not loaded: libpthread.so.0
> Reason: image not found
> Trace/BPT trap: 5

**Comment by FooSoft** [comment]
I'm currently cross-compiling the OSX binaries from a Linux machine, and I'm probably messing something up on the process. As I don't have any machines that run OSX, I'm pulling these downloads until I get them working (and have a way to verify this). 

For now, I recommend using `go get` to build Homemaker locally.

**Comment by christian-schulze** [comment]
No worries, happy to assist in testing or even providing OS X Yosemite builds. I've since pulled/built the code using `go get`, and so far things are working well.

If you don't mind, I'll work on creating a [brew](http://brew.sh/) recipe, which will make this trivial to install on mac machines.

Thanks for writing homemaker btw :+1:

**Comment by FooSoft** [comment]
Glad to hear it worked out. I know people are using Homemaker on OSX, but it seems most people build the bin themselves, which explains why this issue didn't cone up yet.

I appreciate you looking into packaging Homemaker with brew. Let me know once you have it working and I'll add the info to the docs/website :)

**Comment by christian-schulze** [comment]
Do you think Homemaker is at a point where you can start versioning with git tags? Going through the [brew formula cookbook](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md), specifically:

> - has a stable, tagged version (i.e. not just a GitHub repository with no versions). See Interesting-Taps-&-Branches for where pre-release and head-only versions belong.

**Comment by FooSoft** [comment]
If it's something that's required by brew, I don't mind tagging. That being said, I prefer to simply keep the `master` branch in a stable configuration at all times instead, with all untested/broken code in `dev`. 

People using `go get` will always end up grabbing the latest from `master`, so it has to work at all times anyway, making tags be somewhat... redundant?

**Comment by christian-schulze** [comment]
Thats cool, I'll add it to the [head-only](https://github.com/Homebrew/homebrew-head-only) tap.
